chain_one_line_max = 79
fn_args_density = "Compressed"
fn_args_layout = "Visual"
fn_call_style = "Visual"
fn_single_line = true
generics_indent = "Visual"
max_width = 79
reorder_imports = true
reorder_imported_names = true
report_fixme = "Always"
use_try_shorthand = true
